# Generated by Django 4.2.3 on 2023-08-07 08:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('phone_confirmed', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(null=True)),
                ('last_login_ip', models.CharField(max_length=15, null=True)),
                ('date_joined', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('english_first_name', models.CharField(default='', max_length=45)),
                ('english_last_name', models.CharField(default='', max_length=45)),
                ('father_name', models.CharField(default='', max_length=45)),
                ('national_code', models.CharField(default='0000000000', max_length=10)),
                ('passport_no', models.CharField(default='00000000', max_length=8)),
                ('passport_issue_date', models.DateField(null=True)),
                ('passport_expiry_date', models.DateField(null=True)),
                ('gender', models.IntegerField(default=0)),
                ('birthdate', models.DateField(null=True)),
                ('place_of_birth', models.CharField(max_length=45, null=True)),
                ('representative_code', models.CharField(blank=True, max_length=8, null=True)),
                ('education', models.CharField(blank=True, max_length=45, null=True)),
                ('major', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(default='', max_length=15, unique=True)),
                ('home_number', models.CharField(max_length=15, null=True)),
                ('emergency_number', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
                ('postal_code', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('day_of_establishment', models.DateField(null=True)),
                ('national_id', models.CharField(max_length=10, null=True)),
                ('economic_code', models.CharField(max_length=16, null=True)),
                ('ceo', models.CharField(max_length=45, null=True)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('address', models.TextField(null=True)),
                ('postal_code', models.CharField(max_length=10, null=True)),
                ('introduce_letter', models.TextField(null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=16, null=True)),
                ('account_number', models.CharField(max_length=45, null=True)),
                ('sheba_number', models.CharField(max_length=24, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'account_user_bank_account',
            },
        ),
        migrations.CreateModel(
            name='UserConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, null=True)),
                ('type', models.IntegerField(default=1)),
                ('request_date', models.DateTimeField(null=True)),
                ('request_expire', models.DateTimeField(null=True)),
                ('used_date', models.DateTimeField(null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'account_user_confirmation',
            },
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religious', models.IntegerField(default=1)),
                ('nature', models.IntegerField(default=1)),
                ('adventure', models.IntegerField(default=1)),
                ('historical', models.IntegerField(default=1)),
                ('art_cultural', models.IntegerField(default=1)),
                ('shopping', models.IntegerField(default=1)),
                ('energy_class', models.IntegerField(default=1)),
                ('price_class', models.IntegerField(default=1)),
                ('sleep_class', models.IntegerField(default=1)),
                ('accommodation', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'account_user_favorites',
            },
        ),
        migrations.CreateModel(
            name='UserItineraryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'account_user_itinerary_plan',
            },
        ),
        migrations.CreateModel(
            name='UserPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('last_name', models.CharField(max_length=45, null=True)),
                ('english_first_name', models.CharField(max_length=45, null=True)),
                ('english_last_name', models.CharField(max_length=45, null=True)),
                ('national_code', models.CharField(max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('passport_no', models.CharField(max_length=8, null=True)),
                ('passport_issue_date', models.DateField(null=True)),
                ('passport_expiry_date', models.DateField(null=True)),
                ('gender', models.IntegerField(default=0)),
                ('birthdate', models.DateField(null=True)),
            ],
            options={
                'db_table': 'account_user_passenger',
            },
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('point', models.IntegerField(default=0)),
                ('date_validate', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'account_user_point',
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('usage_validate', models.IntegerField(default=1)),
                ('date', models.DateTimeField(null=True)),
                ('point', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'account_user_reward',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ut_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_type',
            },
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('reference_id', models.CharField(max_length=45, null=True)),
                ('type', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('payment_date', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('redirect_code', models.CharField(max_length=45, null=True)),
                ('authority', models.CharField(max_length=45, null=True)),
                ('confirm', models.BooleanField(default=False)),
                ('card_hash', models.CharField(max_length=45, null=True)),
                ('card_number', models.CharField(max_length=16, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aut_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_transaction',
            },
        ),
        migrations.CreateModel(
            name='UserSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(null=True)),
                ('last_modified_date', models.DateTimeField(null=True)),
                ('title', models.TextField(max_length=30, null=True)),
                ('status', models.IntegerField(default=0)),
                ('supporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ausr_supporter', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ausr_type', to='basic.supporttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ausr_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_support_request',
            },
        ),
        migrations.CreateModel(
            name='UserSupportChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('date', models.DateTimeField(null=True)),
                ('attach', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ausc_support', to='accounts.usersupportrequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ausc_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_support_chat',
            },
        ),
        migrations.CreateModel(
            name='UserSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(null=True)),
                ('subscribe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ausu_subscribe', to='basic.subscribe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ausu_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_subscribe',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.IntegerField(default=0)),
                ('theme', models.CharField(default='light', max_length=10, null=True)),
                ('two_step_verification', models.BooleanField(default=False)),
                ('login_sms', models.BooleanField(default=True)),
                ('login_notif', models.BooleanField(default=False)),
                ('login_email', models.BooleanField(default=False)),
                ('withdraw_sms', models.BooleanField(default=True)),
                ('withdraw_notif', models.BooleanField(default=False)),
                ('withdraw_email', models.BooleanField(default=False)),
                ('deposit_sms', models.BooleanField(default=True)),
                ('deposit_notif', models.BooleanField(default=False)),
                ('deposit_email', models.BooleanField(default=True)),
                ('news_sms', models.BooleanField(default=True)),
                ('news_notif', models.BooleanField(default=False)),
                ('news_email', models.BooleanField(default=False)),
                ('rss_sms', models.BooleanField(default=True)),
                ('rss_notif', models.BooleanField(default=False)),
                ('rss_email', models.BooleanField(default=False)),
                ('reserve_sms', models.BooleanField(default=True)),
                ('reserve_notif', models.BooleanField(default=False)),
                ('reserve_email', models.BooleanField(default=False)),
                ('reserve_change_sms', models.BooleanField(default=False)),
                ('reserve_change_notif', models.BooleanField(default=False)),
                ('reserve_change_email', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aus_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_setting',
            },
        ),
        migrations.CreateModel(
            name='UserRewardUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('ip', models.CharField(max_length=15, null=True)),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auru_reward', to='accounts.userreward')),
            ],
            options={
                'db_table': 'account_user_reward_usage',
            },
        ),
    ]
