# Generated by Django 4.2.3 on 2023-08-07 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('basic', '0001_initial'),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreward',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aur_reward', to='club.reward'),
        ),
        migrations.AddField(
            model_name='userreward',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aur_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpoint',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aupo_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpassenger',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aup_country', to='basic.country'),
        ),
        migrations.AddField(
            model_name='userpassenger',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aup_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useritineraryplan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auip_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfavorites',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auf_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userconfirmation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auc_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buba_bank', to='basic.bank'),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buba_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aa_city', to='basic.city'),
        ),
        migrations.AddField(
            model_name='agency',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aa_country', to='basic.country'),
        ),
        migrations.AddField(
            model_name='agency',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aa_province', to='basic.province'),
        ),
        migrations.AddField(
            model_name='agency',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aa_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='au_city', to='basic.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='au_country', to='basic.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='au_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='au_province', to='basic.province'),
        ),
        migrations.AddField(
            model_name='user',
            name='representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='au_representative', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='au_type', to='accounts.usertype'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='useritineraryplan',
            unique_together={('user', 'plan')},
        ),
    ]
