# Generated by Django 4.2.3 on 2023-07-13 08:31

import accounts.image_funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.image_funcs.path_and_rename),
        ),
    ]
