# Generated by Django 4.2.3 on 2023-08-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='wallet_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='status',
            field=models.IntegerField(default=0, help_text='0 pending 1 paid 2 canceled 3 refunding 4 refund 5 pending withdraw 6 withdraw'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='type',
            field=models.IntegerField(default=0, help_text='0-4 withdraw   10-14 deposit'),
        ),
    ]
