# Generated by Django 4.2.3 on 2023-07-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='b_day',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
