# Generated by Django 4.2.3 on 2023-08-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userfavorites_accommodation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupportrequest',
            name='identify_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
