# Generated by Django 4.2.3 on 2023-08-26 08:43

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usersupportrequest_identify_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersupportrequest',
            name='identify_no',
            field=models.PositiveIntegerField(blank=True, default=accounts.utils.identify_generator, null=True),
        ),
    ]
