# Generated by Django 4.2.3 on 2023-08-26 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usersupportrequest_identify_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersupportrequest',
            name='supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ausr_supporter', to=settings.AUTH_USER_MODEL),
        ),
    ]
