# Generated by Django 4.2.3 on 2023-08-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_usersupportrequest_supporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='agency',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
