# Generated by Django 4.2.3 on 2023-08-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='support',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='support',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='support',
            name='viewer',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
