# Generated by Django 4.2.3 on 2023-07-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_subject_is_child_subject_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='subjects',
        ),
        migrations.AddField(
            model_name='support',
            name='subjects',
            field=models.ManyToManyField(null=True, to='support.subject'),
        ),
    ]
