# Generated by Django 4.2.3 on 2023-07-13 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0003_remove_support_subjects_support_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='viewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scf_viewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
