# Generated by Django 4.2.3 on 2023-07-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_support_viewed_date_alter_support_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='support.subject'),
        ),
    ]
