# Generated by Django 4.2.3 on 2023-07-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_support_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ('-id',)},
        ),
    ]
