# Generated by Django 4.2.3 on 2023-07-10 10:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('location', models.CharField(max_length=45, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('website', models.TextField(null=True)),
                ('star', models.IntegerField(default=0, null=True)),
                ('star_rating', models.FloatField(default=0, null=True)),
                ('reservable', models.BooleanField(default=True)),
                ('is_foreign', models.BooleanField(default=False)),
                ('latitude', models.FloatField(default=0, null=True)),
                ('longitude', models.FloatField(default=0, null=True)),
                ('description', models.TextField(null=True)),
                ('grs_id', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('icon', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationFeatureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('accommodation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baru_accommodation', to='basic.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationRuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('english_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('description', models.TextField(null=True)),
                ('accommodation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bas_accommodation', to='basic.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('logo', models.TextField(null=True)),
                ('color_first', models.CharField(max_length=7, null=True)),
                ('color_last', models.CharField(max_length=7, null=True)),
                ('color_code', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('english_name', models.CharField(max_length=45, null=True)),
                ('iata', models.CharField(max_length=10, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=8)),
                ('description', models.TextField(null=True)),
                ('is_province_capital', models.BooleanField(default=False)),
                ('is_country_capital', models.BooleanField(default=False)),
                ('grs_id', models.IntegerField(default=0)),
                ('has_plan', models.BooleanField(default=False)),
                ('usage_flight', models.IntegerField(default=0)),
                ('usage_accommodation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.TextField()),
                ('ceo', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('website', models.TextField()),
                ('address', models.TextField()),
                ('agency_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('english_name', models.CharField(max_length=45, null=True)),
                ('continental', models.CharField(max_length=15, null=True)),
                ('prefix_number', models.CharField(max_length=5, null=True)),
                ('iata', models.CharField(max_length=45, null=True)),
                ('description', models.TextField(null=True)),
                ('grs_id', models.IntegerField(null=True)),
                ('nationality', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('english_name', models.CharField(max_length=45, null=True)),
                ('description', models.TextField(null=True)),
                ('grs_id', models.IntegerField(null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bp_country', to='basic.country')),
            ],
        ),
        migrations.CreateModel(
            name='SiteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.TextField(null=True)),
                ('option_value', models.TextField(null=True)),
                ('option_title', models.TextField(null=True)),
                ('option_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True, unique=True)),
                ('english_name', models.CharField(max_length=45, null=True, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('discount_three_month', models.FloatField(default=0)),
                ('discount_six_month', models.FloatField(default=0)),
                ('discount_one_year', models.FloatField(default=0)),
                ('color_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('capacity', models.IntegerField(default=1)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('english_name', models.CharField(max_length=100, null=True)),
                ('type', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('popularity', models.PositiveBigIntegerField(default=0)),
                ('iata', models.CharField(max_length=45, null=True)),
                ('is_international', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=8)),
                ('address', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bt_city', to='basic.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bt_country', to='basic.country')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bt_province', to='basic.province')),
            ],
        ),
        migrations.CreateModel(
            name='SupportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('icon', models.CharField(max_length=45, null=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bst_father', to='basic.supporttype')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('subscribe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bso_subscribe', to='basic.subscribe')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bci_country', to='basic.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bci_province', to='basic.province'),
        ),
        migrations.CreateModel(
            name='AccommodationServiceCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('english_name', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basc_service', to='basic.accommodationservice')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('english_name', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barc_rule', to='basic.accommodationrule')),
            ],
        ),
        migrations.AddField(
            model_name='accommodationrule',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baru_category', to='basic.accommodationrulecategory'),
        ),
        migrations.CreateModel(
            name='AccommodationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grs_id', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('capacity', models.IntegerField(default=1, null=True)),
                ('extra_capacity', models.IntegerField(default=1, null=True)),
                ('single_bed_count', models.IntegerField(default=1, null=True)),
                ('double_bed_count', models.IntegerField(default=1, null=True)),
                ('sofa_bed_count', models.IntegerField(default=1, null=True)),
                ('out_of_service', models.BooleanField(default=False)),
                ('accept_child', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('accommodation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bar_accommodation', to='basic.accommodation')),
                ('features', models.ManyToManyField(related_name='bar_features', to='basic.accommodationfeature')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationPOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi', models.CharField(max_length=45, null=True)),
                ('distance', models.IntegerField(default=0)),
                ('walk_time', models.IntegerField(default=0)),
                ('drive_time', models.IntegerField(default=0)),
                ('accommodation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bapoi_accommodation', to='basic.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(null=True)),
                ('alt', models.TextField(null=True)),
                ('caption', models.TextField(null=True)),
                ('grs_name', models.TextField(null=True)),
                ('accommodation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bai_accommodation', to='basic.accommodation')),
            ],
        ),
        migrations.AddField(
            model_name='accommodationfeature',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baf_category', to='basic.accommodationfeaturecategory'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ba_city', to='basic.city'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ba_country', to='basic.country'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='features',
            field=models.ManyToManyField(related_name='ba_features', to='basic.accommodationfeature'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ba_province', to='basic.province'),
        ),
    ]
