# Generated by Django 4.2.3 on 2023-07-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_terminal_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
