# Generated by Django 4.2.3 on 2023-08-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_accommodation_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='color_last',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
