# Generated by Django 4.2.3 on 2023-07-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_accommodation_check_in_accommodation_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
