# Generated by Django 4.2.3 on 2023-07-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_city_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodationfeaturecategory',
            options={'verbose_name_plural': 'Accommodation feature categories'},
        ),
        migrations.AlterModelOptions(
            name='accommodationrulecategory',
            options={'verbose_name_plural': 'Accommodation rule categories'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='subscribeoptions',
            options={'verbose_name_plural': 'Subscribe options'},
        ),
    ]
