# Generated by Django 4.2.3 on 2023-07-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_alter_accommodationfeaturecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='accommodationfeature',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='accommodationfeaturecategory',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Accommodation feature categories'},
        ),
        migrations.AlterModelOptions(
            name='accommodationimage',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='accommodationpoi',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='accommodationroom',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='accommodationrule',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='accommodationrulecategory',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Accommodation rule categories'},
        ),
        migrations.AlterModelOptions(
            name='accommodationrulecondition',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='accommodationservice',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='accommodationservicecondition',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='siteoption',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='subscribeoptions',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Subscribe options'},
        ),
        migrations.AlterModelOptions(
            name='supporttype',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('-id',)},
        ),
    ]
