# Generated by Django 4.2.3 on 2023-07-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_alter_continental_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continental',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='basic.continental'),
        ),
    ]
