# Generated by Django 4.2.3 on 2023-07-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_alter_country_continental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continental',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
