# Generated by Django 4.2.3 on 2023-07-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_alter_country_continental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continental',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='basic.continental'),
        ),
    ]
