# Generated by Django 4.2.3 on 2023-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_alter_country_continental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='prefix_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
