# Generated by Django 4.2.3 on 2023-07-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_alter_country_prefix_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefixNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
    ]
