# Generated by Django 4.2.3 on 2023-07-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_continental_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
