# Generated by Django 4.2.3 on 2023-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0018_accommodation_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
