# Generated by Django 4.2.3 on 2023-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_accommodation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='location',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
