# Generated by Django 4.2.3 on 2023-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0020_alter_accommodation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, related_name='ba_features', to='basic.accommodationfeature'),
        ),
    ]
