# Generated by Django 4.2.3 on 2023-07-31 06:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('type', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('amount', models.IntegerField(default=0)),
                ('max_amount', models.PositiveIntegerField(default=0)),
                ('required_point', models.IntegerField(default=0)),
                ('desc_title', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('usage_validate_per_user', models.IntegerField(default=1)),
                ('usage_validate_total', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('hash_prefix', models.CharField(max_length=6, null=True)),
                ('avatar', models.TextField(null=True)),
                ('icon', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('icon', models.CharField(max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TopFiveUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_one', models.CharField(max_length=45, null=True)),
                ('user_two', models.CharField(max_length=45, null=True)),
                ('user_three', models.CharField(max_length=45, null=True)),
                ('user_four', models.CharField(max_length=45, null=True)),
                ('user_five', models.CharField(max_length=45, null=True)),
                ('user_point_one', models.IntegerField(default=0)),
                ('user_point_two', models.IntegerField(default=0)),
                ('user_point_three', models.IntegerField(default=0)),
                ('user_point_four', models.IntegerField(default=0)),
                ('user_point_five', models.IntegerField(default=0)),
                ('date', models.DateField(null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RewardUsageGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.TextField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crug_reward', to='club.reward')),
            ],
        ),
        migrations.CreateModel(
            name='RewardUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all', models.BooleanField(default=False)),
                ('all_transport', models.BooleanField(default=False)),
                ('accommodation_all', models.BooleanField(default=False)),
                ('tour_all', models.BooleanField(default=False)),
                ('airplane', models.BooleanField(default=False)),
                ('train', models.BooleanField(default=False)),
                ('bus', models.BooleanField(default=False)),
                ('hotel', models.BooleanField(default=False)),
                ('other_accommodation', models.BooleanField(default=False)),
                ('tour', models.BooleanField(default=False)),
                ('subscribe_low_all', models.BooleanField(default=False)),
                ('subscribe_low_one_month', models.BooleanField(default=False)),
                ('subscribe_low_three_month', models.BooleanField(default=False)),
                ('subscribe_low_six_month', models.BooleanField(default=False)),
                ('subscribe_low_one_year', models.BooleanField(default=False)),
                ('subscribe_med_all', models.BooleanField(default=False)),
                ('subscribe_med_one_month', models.BooleanField(default=False)),
                ('subscribe_med_three_month', models.BooleanField(default=False)),
                ('subscribe_med_six_month', models.BooleanField(default=False)),
                ('subscribe_med_one_year', models.BooleanField(default=False)),
                ('subscribe_high_all', models.BooleanField(default=False)),
                ('subscribe_high_one_month', models.BooleanField(default=False)),
                ('subscribe_high_three_month', models.BooleanField(default=False)),
                ('subscribe_high_six_month', models.BooleanField(default=False)),
                ('subscribe_high_one_year', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('reward', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cru_reward', to='club.reward')),
            ],
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crr_reward', to='club.reward')),
            ],
        ),
        migrations.AddField(
            model_name='reward',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cr_category', to='club.rewardcategory'),
        ),
        migrations.AddField(
            model_name='reward',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cr_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
