# Generated by Django 4.2.3 on 2023-08-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_rewardrule_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardusageguide',
            name='reward',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crug_reward', to='club.reward'),
        ),
    ]
