# Generated by Django 4.2.3 on 2023-07-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
